"""
FastAPI backend for the AI Shopping Assistant.

This replaces the Streamlit UI with two HTTP endpoints that any frontend
(the React app in ../frontend, curl, Postman, whatever) can call:

  POST /api/chat            { session_id, message }        -> { response }
  POST /api/chat/image       multipart: session_id, file    -> { response }

The agent, tools, and database logic in shopping_agent.py / reviews_api.py /
setup_db.py are untouched — this file is purely the web-serving layer.
"""

import os
import shutil
import tempfile
import uuid

from dotenv import load_dotenv
from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

from shopping_agent import agent

load_dotenv()

app = FastAPI(title="AI Shopping Assistant API", version="1.0.0")

# ---------------------------------------------------------------------------
# CORS — allow the local Vite dev server, plus whatever origin you deploy the
# frontend to (set FRONTEND_ORIGIN in the backend's .env once you host it).
# ---------------------------------------------------------------------------
origins = ["http://localhost:5173", "http://127.0.0.1:5173"]
if extra_origin := os.getenv("FRONTEND_ORIGIN"):
    origins.append(extra_origin)

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# In-memory session store.
#
# Good enough for a demo/portfolio project: each browser tab gets a
# session_id (generated by the frontend and kept in localStorage), and we
# keep that session's message history in a plain dict for as long as the
# server process is running. Restart the server and history resets.
#
# For anything you want to survive restarts or run across multiple server
# instances, swap this dict for Redis or a database table — the rest of the
# code doesn't need to change, only get_history()/save_history() below.
# ---------------------------------------------------------------------------
SESSIONS: dict[str, list[dict]] = {}

# Caps how many turns a single session can rack up. This isn't really about
# cost (Groq's free tier has no card on file, so it can't bill you — it just
# rate-limits), it's about making sure one visitor to your demo can't eat the
# whole shared rate limit while other visitors are trying it out.
MAX_MESSAGES_PER_SESSION = 40


def get_history(session_id: str) -> list[dict]:
    return SESSIONS.setdefault(session_id, [])


def run_agent(history: list[dict]) -> str:
    """Invoke the agent and translate Groq rate-limit errors into a clean 429."""
    try:
        result = agent.invoke({"messages": history})
    except Exception as exc:  # Groq's client raises its own exception types here
        message = str(exc)
        if "429" in message or "rate_limit" in message.lower():
            raise HTTPException(
                status_code=429,
                detail="The AI backend is rate-limited right now (this demo runs on "
                       "Groq's free tier). Please try again in a minute.",
            )
        raise HTTPException(status_code=500, detail=f"Agent error: {message}")

    reply = result["messages"][-1].content.replace("`", "")
    history.append({"role": "assistant", "content": reply})
    return reply


# ---------------------------------------------------------------------------
# Schemas
# ---------------------------------------------------------------------------
class ChatRequest(BaseModel):
    session_id: str
    message: str


class ChatResponse(BaseModel):
    response: str
    session_id: str


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------
@app.get("/api/health")
def health():
    return {"status": "ok"}


@app.post("/api/session/new")
def new_session():
    session_id = str(uuid.uuid4())
    SESSIONS[session_id] = []
    return {"session_id": session_id}


@app.post("/api/chat", response_model=ChatResponse)
def chat(req: ChatRequest):
    history = get_history(req.session_id)

    if len(history) >= MAX_MESSAGES_PER_SESSION:
        raise HTTPException(
            status_code=429,
            detail="This session has reached its message limit for the demo. "
                   "Start a new session to keep chatting.",
        )

    history.append({"role": "user", "content": req.message})
    reply = run_agent(history)
    return ChatResponse(response=reply, session_id=req.session_id)


@app.post("/api/chat/image", response_model=ChatResponse)
async def chat_with_image(session_id: str = Form(...), file: UploadFile = File(...)):
    history = get_history(session_id)

    if len(history) >= MAX_MESSAGES_PER_SESSION:
        raise HTTPException(status_code=429, detail="This session has reached its message limit.")

    suffix = os.path.splitext(file.filename or "")[1] or ".jpg"
    with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
        shutil.copyfileobj(file.file, tmp)
        image_path = tmp.name

    prompt = (
        "I uploaded a product image. Please analyze it and find similar products "
        f"in the store. Image path: {image_path}"
    )
    history.append({"role": "user", "content": prompt})

    try:
        reply = run_agent(history)
    finally:
        os.unlink(image_path)

    return ChatResponse(response=reply, session_id=session_id)


# ---------------------------------------------------------------------------
# Serve the built React app (frontend/dist copied here as "static") when it's
# present — i.e. when this container is running as a single combined deploy
# (see the root Dockerfile). Mounted last, so it only catches requests that
# didn't match an /api/* route above. In local dev you run the Vite dev
# server separately, so this directory won't exist and nothing changes.
# ---------------------------------------------------------------------------
_static_dir = os.path.join(os.path.dirname(__file__), "static")
if os.path.isdir(_static_dir):
    app.mount("/", StaticFiles(directory=_static_dir, html=True), name="static")
